Xjph/ObservatoryCore

ObservatoryCore/UI/ViewModels/BasicUIViewModel.cs, ObservatoryCore/UI/ViewModels/CoreViewModel.cs, ObservatoryCore/UI/Views/BasicUIView.axaml.cs
Upon arrival of new records to the backing ObservableCollection, scroll the DataGrid to the last item. However, when the DataGrid is initialized, there's not yet a data context set, so when that happens, then we can listen to the CollectionChanged event to trigger scrolling (only really needed for additions).
In passing, also set the DataGrid to ReadOnly.
In the other two files, minor simplifications/cleanup.
=> Implement scrolling BasicUIView grids to the bottom plus refactoring

ObservatoryCore/LogMonitor.cs, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/UI/Views/BasicUIView.axaml.cs
The first time you click "Start monitor" (assuming you haven't read-all), we read the last 2 log files to find the journal entries for the last system jumped into (if we can find the FSDJump entry) in order to re-populate the information in all interested plugins. Its much faster than reading all to restore current system context.
- For Botanist plugin, this will display what plants/planets you've already sampled and avoids placeholder planet entries with incorrect bio counts.
- For Explorer, it re-lists interesting items, in case you weren't done exploring the system.
A baby step for Xjph/ObservatoryCore#5
=> Implement "Pre-reading" of current system context when starting monitor

ObservatoryCore/LogMonitor.cs, ObservatoryCore/UI/ViewModels/CoreViewModel.cs
This has the effect of suppressing notifications when restoring current system context after initial click on "Start Monitor".
Split out from https://github.com/Xjph/ObservatoryCore/pull/10.
=> Make Pre-read act similarly to "Read All"

ObservatoryCore/ObservatoryCore.cs, ObservatoryCore/ObservatoryCore.csproj, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/MainApplication.axaml, ObservatoryCore/UI/Models/NotificationModel.cs, ObservatoryCore/UI/ViewModels/NotificationViewModel.cs, ObservatoryCore/UI/Views/BasicUIView.axaml.cs, ObservatoryCore/UI/Views/NotificationView.axaml, ObservatoryCore/UI/Views/NotificationView.axaml.cs
Change basic notification to something more presentable, and added several settings to control it.
Also snuck in the basic properties migration from older versions so they won't be lost between updates now that we have more of them. Still need to do this for plugin settings though.
=> feat: cosmetic overhaul of native notification popup

ObservatoryCore/NativeNotification/NativePopup.cs
Manipulating active notifications must be done on the Avalonia UI thread. UpdateNotification and CloseNotification were not properly doing this.
Any plugin attempting to use persistent notifications would have encountered these errors.
NOTE: There is not yet hooks for cleaning up persistent/infinite timeout notifications when the APP is closed.
=> Fix a couple of invalid thread exceptions in NativePopup notifications

ObservatoryCore/LogMonitor.cs
System context pre-reading logic previously assumed the player jumped into the current system in their own ship as a pilot. Arriving docked on their carrier was thus missed and may have resulted in processing more than one systems worth of context (or simply failing to pre-read context).
=> When pre-reading current system context, consider docked Carrier jumps

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryFramework/EventArgs.cs
Plugins authors can now optionally specify what ways their notifications are rendered (subject, of course, to user preferences/settings). The default is to render notifications in all available channels. Examples:
- Show native pop-up window only (ie. no voice/plugin notifiers)
- Disallow other plugin notifiers
This does not support selection of notifier plugins.
Furthermore, persistent notification updates were not previously being forwarded to anything but the native popup notifier. Now plugins and native voice are also supported (subject to user preferences) and respect the new rendering controls added here. There is currently no concept of closing notifications for the native voice or plugin-based notifiers.
=> Add new Rendering controls for notifications, add missing forwarding

ObservatoryFramework/Files/Journal/Startup/Cargo.cs
Discovered when attempting to handle this event for an in-progress plugin.
=> Fix incorrect type for the Cargo.Inventory property

ObservatoryCore/PluginManagement/PluginManager.cs
Added a second condition to the Observatory.Framework assembly loading check to prevent a stack overflow condition.
=> For some reason this check failed and resulted in a stack overflow

ObservatoryBotanist/Botanist.cs, ObservatoryBotanist/BotanistSettings.cs
When first sample is taken, the notification is displayed showing what was sampled and number of samples taken. Number of samples taken is updated on the second sample. Notification is removed when the final sample is taken.
=> Show notification with genetic sampling status while in progress

ObservatoryFramework/ObservatoryFramework.xml
This functionality was originally added in #47.
=> Add missing docs for new NotificationArgs.Rendering enum

ObservatoryExplorer/DefaultCriteria.cs
Reverts Xjph/ObservatoryCore#56
I wasn't thinking when I merged this. This issue has been discussed on the forums with the conclusion being to leave it in as intended functionality. Close *belt* proximity can give unique [views of planets from asteroid clusters.](https://forums.frontier.co.uk/threads/elite-observatory-search-your-journal-for-potentially-interesting-objects-or-notify-you-of-new-ones-on-the-fly-while-exploring.521544/page-20#post-8192352)
=> Revert "Close Ring Proximity criteria: Prevent it from triggering on a belt"

ObservatoryBotanist/Botanist.cs, ObservatoryCore/LogMonitor.cs, ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginEventHandler.cs, ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/UI/ViewModels/CoreViewModel.cs, ObservatoryExplorer/Worker.cs, ObservatoryFramework/EventArgs.cs, ObservatoryFramework/Interfaces.cs
Pre-reading hackily used read-all to suppress notifications. But that broke some assumptions about what read-all meant. Furthermore, the Core UI told plugins about read-all rather than the log monitor telling them -- which is really what should be telling them.
To address these concerns, LogMonitor now provides an event that both the PluginCore and PluginEventHandler listens to for tracking logging state allowing more granular information about the activities of LogMonitor, including distinguishing between ReadAll and Pre-read batches. Plugins no longer need to track if LogMonitor is in batch-read mode or not -- PluginCore now provides it. 
I've also converted all built-in plugins to use the new event-based system. The old system is marked deprecated and will go away once other known …
=> Add event-based LogMonitor state changes to better handle batch reads

ObservatoryCore/LogMonitor.cs, ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginManager.cs
The order that listeners get notified isn't deterministic and as a result plugins which read the current state from PluginCore during the handling of a state change event may read a stale state resulting in unexpected results. PluginCore now reads a property directly from LogMonitor to avoid such inconsistencies.
=> Revert PluginCore use of event listening for current LogMonitor state

ObservatoryCore/LogMonitor.cs
With U11's new filename format for journal files, files don't sort right anymore and so the incorrect context was read during pre-reading, journals were read out-of-order during read-all or the wrong file was poked by JournalPoke for real-time. It seems that real-time still worked well enough (presumably the game client flushes journals semi reliably?)
Either way, ordering can be better guaranteed now.
=> Fix file ordering assumptions which were broken by U11

ObservatoryExplorer/DefaultCriteria.cs
If it's a belt, report it as a belt instead of a ring.
See 7c209efb9f1e4eeb248b36d65463aa10e6f2f70e for context.
=> Distinguish Close Belt proximity and Close Ring proximity criteria

ObservatoryCore/UI/Views/BasicUIView.axaml.cs
Random occurrence triggered by a plugin's grid update. It's either fairly rare (related to something I was doing in-app) or new with a recent update to the plugin that caused it (just updated it last night).
=> Fix a "Call from invalid thread" exception.

ObservatoryCore/ObservatoryCore.cs, ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryExplorer/CustomCriteriaManager.cs, ObservatoryExplorer/Explorer.cs, ObservatoryFramework/Interfaces.cs, ObservatoryHerald/HeraldNotifier.cs, ObservatoryHerald/HeraldQueue.cs, ObservatoryHerald/SpeechRequestManager.cs
Fixes #77
This adds an error logging method on the IObservatoryCore interface that writes the exception details to ObservatoryCore's central error log (found in `${Documents}/ObservatoryErrorLog.txt`). In addition, added a timestamp to each error log.
Also updates the Explorer to report Custom Criteria file load errors and execution errors to the log. Also updates HeraldNotifier to report CacheIndex.json parse failures to the error log as well.
=> Expose core error logger to plugins and report custom criteria errors

ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/ViewModels/BasicUIViewModel.cs, ObservatoryCore/UI/ViewModels/CoreViewModel.cs, ObservatoryCore/UI/Views/BasicUIView.axaml.cs, ObservatoryCore/UI/Views/CoreView.axaml, ObservatoryCore/UI/Views/NotificationView.axaml.cs, ObservatoryFramework/ObservatoryFramework.xml, ObservatoryHerald/SpeechRequestManager.cs
Probably should've separate concerns a bit better here.
- Implement basic data export for generic grid views
- Fix possible stack overflow when loading plugin dependencies
- Automatically extract plugins in `.zip` format (or renamed to `.eop`)
- Handle possible file locking from Herlad cache update race condition
=> Export, plugin archive install, and herald cache race condition fixes

ObservatoryExplorer/DefaultCriteria.cs
Just checking something is not already discovered is not enough. Many valuable bodies in the bubble mis-fire this criteria because the journal reports them as not discovered (because they have no first discoverer because they're well known systems). Checking that they're also not mapped ensures this doesn't happen.
Also simplified rendering of the string info.
=> Workaround journal bug: Already mapped bodies are not undiscovered

ObservatoryCore/LogMonitor.cs
Symptoms: App takes a very long time to start up, sluggish response to events because it's reading and processing every ancillary file 10x instead of just once when successful.
=> Fix boolean logic bug that slows ancillary file reading to a crawl

ObservatoryCore/UI/Views/NotificationView.axaml.cs
The recently updated avalonia seemed to change behavior in a way that caused notifications to steal focus from the game (often at at inopportune times). Not all users experienced this.
=> Disable ShowActivated on notifications to avoid focus stealing

ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/ViewModels/CoreViewModel.cs, ObservatoryCore/UI/Views/BasicUIView.axaml.cs
Tab separated output facilitates much more efficient opening of exported content in a spreadsheet for further data analysis, furthermore, it vastly reduces file size at the cost of human-readability. However, for the spreadsheet junkies among us, this is a welcome option.
To complement this, there is now an "Export Options" expander in the Core settings panel. Here one can select their preferred export style (default remains Fixed width) and now one can pre-select the export folder.
With this change, clicking export *will not* prompt for an export folder if one is already set. It will simply immediately export data.
=> Implement Tab separated export format

ObservatoryCore/PluginManagement/PluginEventHandler.cs
I've had this occur a number of times (twice in a row yesterday) where if you receive new records while doing a long read-all, this exception crashes ObsCore.
So may need some further digging, but in the meantime, it won't crash here.
=> Handle disposed timer object in ResetTimer()

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryFramework/Interfaces.cs
For plugin developers: Adds a new method to the IObservatoryCore interface to add multiple grid items in 1 call -- which only invokes the UI thread once (and potentially only scrolls to bottom once) providing a small performance improvement and providing some modest convenience.
=> [Framework + Core] Feature: Add support for adding multiple grid items

ObservatoryCore/UI/Views/NotificationView.axaml.cs
This PR adds a Linux (X11) implementation for "transparent" windows. This implementation only works on the X11 window system, which is used on I would say most Linux machines.
I'm quite inexperienced with C#, so please let me know if there's anything I need to change. I'm not sure if ignoring exceptions is the way to go here, but this seemed like the easiest way.
=> Implement click-through windows for X11 (Linux)

ObservatoryCore/UI/Views/NotificationView.axaml.cs
There's a small bug on Linux where notification windows are spawned in the middle of the primary screen. This PR addresses this bug by updating the position of the window right after `Show()` is called.
=> Update notification window position on Show()

ObservatoryCore/LogMonitor.cs, ObservatoryCore/UI/ViewModels/CoreViewModel.cs
Add a try-catch in ReadAllLines to handle a read failure if a file is locked.
Add a check for a non-existing export folder when exporting and prompt for new path if it doesn't exist.
=> 2 Bug Fixes

ObservatoryFramework/Files/Journal/FleetCarrier/CarrierJumpRequest.cs, ObservatoryFramework/Files/Journal/JournalBase.cs, ObservatoryFramework/Files/ParameterTypes/CurrentGoal.cs
Refactored out the logic backing the JournalBase TimestampDateTime property so it can be used for any DateTime type property, providing a standardized json String -> DateTime conversion for any date-time property. Implemented as an `internal static` method on JournalBase so journal objects which inherit from JournalBase or don't inherit from it can use it.
Used this to provide a DepatureTimeDateTime on CarrierJumpRequest (this property was added in Update 14) and to implement the existing ExpiryDateTime on CurrentGoal.
From a quick search in the journal documentation, I don't see any other applications for this.
=> [Framework] Add a DateTime property for CarrierJumpRequest DepartureTime

ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/SettingsForm.Designer.cs, ObservatoryCore/UI/SettingsForm.cs, ObservatoryFramework/Files/Journal/FleetCarrier/CarrierJumpRequest.cs, ObservatoryFramework/Files/Journal/JournalBase.cs, ObservatoryFramework/Files/ParameterTypes/CurrentGoal.cs
Polishing a few rough edges with the Core/Settings UI:
* Enable scrolling on the Plugin List view. It only fit 6 or 7. I have 13. Really hard to access settings.
* I fiddled a bit with column auto-sizing (left it commented out, see comment, but I'd like to see if this can be improved further).
* A whole bunch of tweaks to the settings view:
* first row of controls was cut off at the top (under the window title bar)
* fixing that revealed uneven spacing between columns (ie. second column of checkboxes had a blank space at the top)
* action buttons were teensy tiny and unreadable
* settings view columns were too narrow, most labels were cut off (only 200 px wide) -- some still are cut off.
* added some spacing to help with readability
* settings windows now start in center of current screen …
=> [Observatory Core] New UI tweaks round 1

ObservatoryCore/UI/CoreForm.Plugins.cs, ObservatoryCore/UI/CoreForm.cs
After populating the list of plugins, auto-size the columns once. In the Resize event handler, do what you did before but account for the scrollbar width too. Prevents horizontal scrollbar appearing except for really fast resize movements.
I didn't try it yet with fewer than a scrollable # of plugins yet.
This cleans up my commented out code from #128.
=> [Core] Improve(?) Plugin List column sizing

ObservatoryHerald/HeraldNotifier.cs
This makes Herald, a plugin ONLY react to NativeVocal notifications so notifications can be sent silently by using `Rendering = NotificationRendering.PluginNotifier` on NotificationArgs. These notifications will be picked up by other notification listeners (eg. Aggregator).
=> [Herald] Herald as native voice

ObservatoryExplorer/Explorer.cs, ObservatoryFramework/EventArgs.cs, ObservatoryFramework/ObservatoryFramework.xml
The new properties are:
* string Sender: The name of the plugin sending the notification.
* string ExtendedDetails: Even more detail than Title and Detail convey. This value will not be spoken nor included in pop-up notifications. However, other notifier plugins may use this value.
* int ColescingId: An id which can be used to correlate multiple notifications together (ie. for sorting/grouping) without depending on arbitrary string values. I recommend reserving -1 for system, 0 .. 1000 for system bodies and anything else is arbitrary and can be agreed upon between Core and Plugin authors, as desired.
While the motivating use is a new notifier plugin I am authoring (my Aggregator plugin, see GitHub), I have tried to make this as general purpose as possible.
I have modified Explorer as an …
=> [Framework] Add 3 new properties to NotificationArgs to expand detail

ObservatoryCore/UI/SettingsForm.cs
Attempting to set decimal values to int properties tends to throw errors. ;-)
=> [Core] Fix: Convert Decimal control values to int32 for Int settings

ObservatoryExplorer/CustomCriteriaManager.cs, ObservatoryExplorer/DefaultCriteria.cs, ObservatoryExplorer/Explorer.cs
For Custom Criteria:
* You can now disable a CC by inserting a `--` in the first line of the criteria; eg: `::--Criteria::`
* If a custom criteria throws an error or fails to parse/load, Core no longer disables custom criteria entirely -- it now disables the problematic criteria until you update the custom criteria file and trigger a new journal/re-read (which reloads the source file).
For Default Criteria:
* Adds landable status of the body triggering the Close Ring/Belt proximity. (Requested in Discord somewhere.)
* Adds the triggering ring name to the Wide Ring criteria. (I believe also requested, can't remember now.)
=> [Explorer] Default + Custom Criteria improvements

ObservatoryBotanist/Botanist.cs, ObservatoryBotanist/BotanistSettings.cs
Previously the Sampler overlay notification was sticky (ie. it stuck around until you completed sampling). This change adds an option (by request) to make it not-sticky (so it disappears after the configured timeout, like other notifications). Default will be sticky.
It was also observed that for non-English users, all the colony distances were 100m (effectively default) because the Genus_Localised field was being used for lookups, failing and thunking to default. Furthermore, the notification would display a mix of languages. With this update, we use the identifier (ie. the Genus field) and map to English names and this should provide consistent language output and lookup of colony distances. This also adds support for Horizons bios that can be sampled.
2 minor changes to support the …
=> [Botanist] Localization fixes, setting for sampler overlay, ui overhaul

ObservatoryBotanist/BotanistSettings.cs, ObservatoryCore/UI/SettingsForm.cs, ObservatoryExplorer/ExplorerSettings.cs, ObservatoryFramework/Attributes.cs, ObservatoryFramework/ObservatoryFramework.xml
Layout improvements:
* Plugins can set `[SettingSuggestedColumnWidth(123)]` on a settings class to adjust the settings view column width to make it wider or narrower to fit things nicely.
* Plugins can set `[SettingNewGroup("label")]` on any setting property to force a "new paragraph", or group, of settings. If "label" is also provided, a grouping header with that text will also be created.
* A double precision up/down numeric control has been added. In support of this, there is now a precision value on the existing `[SettingNumericBounds]` attribute to specify the number of digits of precision the control displays/allows. Note that the slider is not available for doubles as the slider has only int granularity itself.
Plugins:
* The above have been applied/demonstrated on the Botanist and …
=> [Core] Settings improvements: Grouping w/labels, support for doubles

ObservatoryCore/App.config, ObservatoryCore/PluginManagement/PluginEventHandler.cs, ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.Plugins.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/PluginHelper.cs
Add checkboxes to the PluginList which allow you to enable/disable each plugin on-the-fly (it will no longer respond to events, but you can still configure it, etc.). These settings are preserved in a new Core setting. Also enabled full-row select for easier selection in the listview.
Also increased the height of the PluginList slightly. (Personally, I'd like it even taller.)
Also made slight sizing adjustments to the plugin tabs, which now show 3 letters when collapsed and has a bit of extra space so the longest one does not get cut-off when selected/bolded. Furthermore, the list of plugins is now sorted alphabetically.
Finally, set the plugin listview Dock = Fill (vs. Anchored).
=> [Core] Spit and polish on PluginList and tabs

ObservatoryCore/PluginManagement/PluginCore.cs
Just shuffled code within conditional compiler directives because when publishing, it seems "RELEASE" is not set. This ensures in the non PORTABLE case, the default path is set.
(Discovered while testing my publishing script with signing.)
=> [Core] Fix "not all code paths return a value" error when publishing

ObservatoryCore/ObservatoryCore.cs, ObservatoryCore/Utils/LogMonitor.cs
Pre-reading is good. And turns out a number of plugins kinda depend on it now. Time to make it default.
Also, uncomment settings upgrades so settings are carried over from version to version when running in the IDE -- which makes using it far better.
=> [Core] Make Prereading the default behavior, re-enable settings upgrade

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/PluginHelper.cs, ObservatoryCore/UI/PluginListView.cs, ObservatoryFramework/Interfaces.cs, ObservatoryFramework/ObservatoryFramework.xml
This proposes a *new method* on IObservatoryCore:  `SetGridItems(worker, items)` which does 2 things:
* Clears the grid
* Adds the given items.
Effectively replaces the entire content of the grid -- which is something a handful of plugins now do.
Why add this when you could just call Core's Clear + AddGridItems methods?? So it can all be done within the same rendering suppression "scope" to reduce flickering and increase rendering speed.  Speaking of rendering suppression, I have implemented such rendering suppression "scope" which uses Listview's built-in Begin/EndUpdate() in combination with temporary removal of the sort comparer (as is done for read-alls).  This was also applied to the existing AddGridItems(worker, items) method as well, addressing a TODO.
=> [Core + Framework] Performance improvements for re-drawing the grid

ObservatoryFramework/EventArgs.cs
While testing, I discovered that plugins that don't yet support sending the Coalescing ID were not mixing well because the default value of the ID is 0 -- which is also a valid body id. If the default is null, receivers can detect the absent value and apply a sensible default (ie. group them where it makes sense).
=> [Framework] Make the new CoalescingId event arg nullable

ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/NotificationForm.Designer.cs, ObservatoryCore/UI/NotificationForm.cs, ObservatoryCore/UI/ThemeManager.cs
- Notification title was previously missing; it's back!
- Fixed window and label backgrounds to be correctly/consistently transparent.
- Reduced title size to avoid wrapping. Moved the body text up a few pixels to close the larger gap between title and body.
- Excluded the colour picker button from theming so it always shows the correct colour.
- Widened the Notification font selector in Core settings to allow distinguishing between variants of large font families.
The click-thru bit is only partially working (transparent areas are click-thru).
=> [Core] Visual improvements to notifications

ObservatoryCore/UI/NotificationForm.cs
Fixed-position notification positioning was off. Finally figured out why... The XPos arg was used for Y position as well.
A classic 1 character fix...
=> [Core] Fix Notification positioning

ObservatoryCore/UI/CoreForm.Plugins.cs
The UI was updated, but internal state was not correct, and disabled plugins would still run. My assumption wasn't fully correct, it appears.
=> [Core] Ensure plugin enabled state is preserved across restarts

ObservatoryHerald/HeraldQueue.cs
If herald's API is down and files failed to be fetched, it caused ObsCore to crash.
This should catch it more gracefully.
=> [Herald] Prevent app crash on failure to retrieve an audio file

ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/SettingsForm.Designer.cs, ObservatoryCore/UI/SettingsForm.cs
Some core settings buttons and settings window buttons were inconsistent with the cluster of 4 buttons at the bottom of the Core window and below the Plugin list. I took those to be the defacto standard.
Applied the following changes to all inconsistent buttons (some programmatically for generated settings UI and the rest via designer):
```
button.FlatStyle = FlatStyle.Flat;
button.FlatAppearance.BorderSize = 0;
```
The only button I didn't touch was the Colour swatch button -- so if the selected colour is the same as the background for some reason, you can still see it.
Before: 
After:
=> [Core] Make button styles consistent throughout the app

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/CoreForm.Plugins.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryFramework/Interfaces.cs, ObservatoryFramework/ObservatoryFramework.xml
Adds two new actions to IObservatoryCore (and implements them):
OpenSettings: Opens the Settings form for the given plugin (presumably the caller).
FocusPlugin: Switches to the plugin tab matching the given plugin shortname (which may be obtained via NotificationArgs.Sender).
=> [Framework + Core] Add OpenSettings and FocusPlugin actions to Core

ObservatoryCore/PluginManagement/PluginManager.cs
New feature, new crash opportunities? Let's try minimize that. :D
Used standard error logging mechanisms.
=> [Core] Handle errors in ObservatoryReady() to avoid crashing app

ObservatoryCore/App.config, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.Settings.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/ThemeManager.cs
After some of the recent work, plugin list scrolling *and* core settings panel scrolling stopped working. While those fixes were relatively trivial, it leads to nested scrolling (ListView + core panel scrolling) which is ... blah.
Soo, did a bit of rearranging:
* Added a Splitter between the plugin list + buttons and the rest of the core settings panels. This allows the user to expand the plugin list view to show more plugins. This also means only 1 scrollbar is necessary in the top half of the view (because the bottom half of the content can scroll independently). The splitter position is saved across app restarts and has been included in default themes to be visible.
* Resized the core settings panels to be consistently sized and added a flow layout panel so regardless of the …
=> fix(core): rework core panel layout to fix scrolling

ObservatoryCore/App.config, ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginEventHandler.cs, ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/Properties/Core.Designer.cs, ObservatoryCore/Properties/Core.settings, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.Plugins.cs, ObservatoryCore/UI/CoreForm.Settings.cs, ObservatoryCore/Utils/AudioHandler.cs, ObservatoryFramework/ObservatoryFramework.xml, ObservatoryHerald/HeraldNotifier.cs, ObservatoryHerald/HeraldQueue.cs, ObservatoryHerald/HeraldSettings.cs
Previously, there was a large volume of volume controls -- which didn't all work:
* Herald/Plugin-provided audio volume doesn't work. Herald had a volume control but it was broken when the audio subsystem was overhauled.
* Native voice volume control worked -- only for native voice.
So now we have 1 volume control to rule them all, now located in core settings, not native voice settings (so always visible/available), which controls ALL audio levels (plugin-provided and native audio). Thus, the Volume setting in Herald is removed.
Of course, to test control of native voice volume, I needed to disable Herald -- which previously required deleting the dll from the plugins folder and restarting the app. That was too much work and doesn't make sense now with the checkboxes in the plugin list to …
=> feat(core,herald): Unify volume settings; make overrides dynamic

ObservatoryExplorer/CustomCriteriaManager.cs
New convenience functions for use in Lua custom criteria.
Interrogation helpers:
* `isBelt(body_name)`
* `isRing(body_name)`
* `isBarycentre(scan)`
Also updated the existing `isPlanet(scan)`function to exclude barycentres.
Conversion helpers:
* `distanceAsLs(value_in_m)`
* `distanceAsKm(value_in_m)`
* `gravityAsG(value_in_mps2)`
* `pressureAsAtm(value_in_pa)`
* `periodAsDay(value_in_s)`
* `periodAsHour(value_in_s)`
There are also new globally available constants related to the unit conversion functions, above:
* `const.SPEED_OF_LIGHT_mps` - the speed of light expressed in meters per second, aka, the constant `c` or 1 Ls.
* `const.GRAVITY_mps2` the acceleration due to gravity expressed in meters per second squared, or 1g.
* `const.ATM_PRESSURE_Pa` the pressure of 1 atm expressed in …
=> feat: [Explorer] Add a few new convenience functions and constants

ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/UI/CoreForm.Plugins.cs
... not just *enabled* plugins. Disabled plugins need to be included because otherwise they don't re-appear when enabled until the app is restarted-- which isn't ideal.
=> fix: [Core] Use all visible plugins for drawing tabs

ObservatoryCore/UI/ReadAllProgress.cs, ObservatoryCore/Utils/LogMonitor.cs, ObservatoryFramework/EventArgs.cs, ObservatoryFramework/ObservatoryFramework.xml
We now have an explicit state that is fired when you cancel a read-all. This is useful for plugins which store state that may be incomplete/unusable if read all is not complete.
State transitions will be as follows: <initial state> -> <initial state> | Batch [-> <initial state> | BatchCancelled] -> <initial state>
The BatchCancelled state is not entered if the read-all run completes normally.
=> feat(core,framework): Add LogMonitorState.BatchCancelled

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryFramework/EventArgs.cs
According to the profiler, this does wasteful allocations, etc. It is recommended to use the bitwise operator. I did some profiling to figure out why a couple of my plugins were slow during read-all, and this came up.
If you like it, accept it. If not, fine too.
=> perf(core,framework): Reduce usage of Enum.HasFlag

ObservatoryCore/NativeNotification/NativeVoice.cs, ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/Utils/AudioHandler.cs, ObservatoryFramework/Interfaces.cs, ObservatoryFramework/ObservatoryFramework.xml, ObservatoryFramework/ParameterTypes.cs
...to avoid breaking audio playback entirely.
* Added an early-out when Enqueuing if the input filename is blank or the file doesn't exist.
* Added additional `File.Exists` checks before attempting a `new FileInfo()` when processing the queue and moved these checks inside try/catch (in case the file was deleted since the early out).
* Added try/catch protection for the instant playback path as well.
* Added a new AudioOptions parameter class to control whether or not the file is deleted after playback. (Unconditionally deleting files, which was intended for NativeVoice audio caused problems for Herald and it's local cache.) These options are also exposed to plugins.
* Tidied up a bunch of UI misalignment (which will likely cause conflicts with #169 ).
* Refactoring
=> fix(core): Improve audio error handling, bug fixes and refactoring

ObservatoryBotanist/Botanist.cs, ObservatoryFramework/Sorters/NoOpColumnSorter.cs
There are likely a few other plugins (ie. any plugin which controls its own grid ordering) which likely want this too, so the idea is to make one many plugins can share to disable sorting in the new UI.
There was already such an implementation in Botanist; moved it to Framework and use it instead.
=> chore(framework,botanist): Add a no-op column sorter to Framework

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.Plugins.cs, ObservatoryCore/UI/CoreForm.Settings.cs
New buttons:
* Plugin Data Folder: Opens the selected plugin's data folder. If no plugin selected, the root plugin data folder. Located below the plugin list.
* Core Config Folder: Opens the location of the ObsCore config. This button is only visible in DEBUG builds (by way of compiler conditions). Located in the top-right corner of the Core Settings box.
To expose the plugin data folders and share logic, I did a bit of refactoring in PluginCore. And it seems CoreForm had no reference to PluginCore -- so made that accessible via PluginManager.
Did a bonus pass over tab indices to make controls sensibly ordered.
=> feat(core): New core buttons, update tab indices

ObservatoryCore/UI/PluginHelper.cs, ObservatoryCore/UI/PluginListView.cs
Selection can be multi-selections as well.
Press Ctrl+C to copy the selected rows (tab separated) to the system clipboard.
What highlighting looks like for the moment (alternating row bg coloring is maintained):
Light theme:
Dark theme:
=> feat(core): Basic grids now support row selection, highlighting, copying

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginEventHandler.cs
MattG reported that targeting ONLY a native notifier (ie. voice or visual) when there was an override in place was not received. We've never noticed that because apparently nobody's targeted *only* NativeVocal and there's no NativeVisual notifiers (yet). (It worked it PluginNotifier was also targeted.)
So yeah, turns out that was not handled correctly; and it's now fixed.
Tested with hacking up my Helm (targeted notification sender) and Aggregator (overriding notification receiver) plugins and Herald.
=> fix(core): Targeted notifications now received by overriding notifiers

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginEventHandler.cs, ObservatoryFramework/Interfaces.cs, ObservatoryFramework/ObservatoryFramework.xml
Add a boolean property to the IObservatoryNotifier interface that allows a plugin to override the default suppression of sending notifications to plugins notifiers. This must be explicitly set by interested plugins so existing notifiers will not suddenly receive all the batch-read notifications.
This has the side benefit of cleaning up a couple bits of duplicate code wrapped in mutually exclusive `#ifdef` blocks.
This will enable some desireable functionality in Aggregator (showing notifications generated via pre-read and some testing via read-all) without negative impact to existing plugins (like telegram and StellarOverlay -- which presently spams me with notifications if I forget to disable it).
=> feat(core,framework): Allow plugins to opt in to batch-mode notifications

ObservatoryCore/UI/ColourableTabControl.cs, ObservatoryCore/UI/CoreForm.Designer.cs, ObservatoryCore/UI/CoreForm.Settings.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/CoreForm.resx, ObservatoryCore/UI/ThemeManager.cs
* Moved the ColourableTabControl.DrawItem event into the ColourableTabControl class itself, out of CoreForm, as discussed.
* Widened the Theme picker drop-down to be the same size as the font drop-down.
* Add some error handling around applying a theme to prevent application crashes if something like an invalid color is applied to certain properties (notably DataGridView's GridColor).
* When adding a theme which already exists, don't duplicate it in the drop-list (it's already de-duped in the manager).
* When adding a theme which is currently selected, reapply it.
* Apply JSON serialization options to make writing a theme file a little more forgiving and less error prone. It also makes the version stored in the settings more compact by omitting null values.
* In Debug mode, spit out a …
=> fix(core): Numerous theme-related fixes and refactoring

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/CoreForm.cs, ObservatoryCore/UI/FormsManager.cs, ObservatoryCore/UI/PluginContextMenu.cs, ObservatoryCore/UI/PopoutForm.cs
After adding popout windows, FocusPlugin would unhelpfully focus an empty tab. Now it activates the existing popout window or switches the main window tab.
Furthermore, when activating plugin settings or about via PluginCore, you could open many many duplicates in some cases. Now, all this goes through a manager (scraped out of the plugin tab context menu handler) which first searches for the window being opened and activates it instead of opening a duplicate, otherwise opens a new. Add similar protection around the Core About button.
All these form handling methods have been refactored into a "FormsManager" class for uniform handling.
Cleaned up a bit of unused stuff as a result of some of this refactoring.
=> fix(core): FocusPlugin activates popout, prevent duplicate windows

ObservatoryCore/UI/SettingsForm.cs
The NumericUpDown control Value property will throw if the value is out of bounds.
This can happen if a plugin sets bounds on a setting that does not include zero but does not initialize the value (typically when adding a new numeric value to a settings config that already exists).
=> fix(core): Clamp numeric settings before assigning to Value

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/FormsManager.cs
Tabs use short name but windows use the full name. The original FocusPlugin implementation used the short name passed in from the calling plugin forwarded to it (likely) from a notification sender. This would only succeed in focusing a popped-out window if the Short name and Full name matched. There are plugins for which this is not true (ie. Commander vs. Fleet Commander).
Update PluginCore to find the plugin instance with the corresponding short name and use pass the plugin instance to the method which can then use either the full name to find the window or the short name to find the tab.
=> fix(core): Minor FocusPlugin fix

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/PluginManagement/PluginEventHandler.cs, ObservatoryFramework/Interfaces.cs, ObservatoryFramework/ObservatoryFramework.xml
Add ability for plugins to send messages to specific plugins instead of always broadcast. Stop senders receiving their own messages. Stop plugins that are both notifiers and workers receiving messages twice.
=> Update Plugin Messaging

ObservatoryFramework/Files/Converters/MaterialCompositionConverter.cs, ObservatoryFramework/Files/Converters/StarPosConverter.cs, ObservatoryFramework/Files/Journal/Exploration/Scan.cs, ObservatoryFramework/Files/Journal/JournalBase.cs, ObservatoryFramework/Files/Journal/Travel/Location.cs
I'm working on something that creates Journal objects and serializes them back to JSON... There are a few shortcomings of the current serialization situation, this is some improvement:
* Add some Converter write-path implementations
* Add a few bits of null handling
* Add JSON property ordering attribute to JournalBase so timestamp and event are emitted first when serializing (I did not go so far as to set this on every class; it's not THAT important). NOTE that the default value is 0, so these are negative. The default is actually quite annoying.
* Apply the MaterialCompositionConverter to Scan.AtmosphereComposition
Nothing here should be breaking. All the other plugins I use compiled and/or ran fine with this change.
=> chore(framework): Improve serialization support in JSON object model

ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/UI/PluginList.cs
Three main changes:
* Plugin settings (the whole value) is no longer parsed for every unique plugin that is loaded.
* Settings load failures will result in plugin settings being reset, and not prevent the whole plugin from loading, nor cause ObsCore crashes. Such cases are now explicitly called out in the plugin list.
* Settings for old plugins are now purged (but only if all plugins successfully load, to avoid oopsies wiping your hard work out). This will reduce the size of plugins settings by a fair amount if you've not cleaned them out recently (due to plugin renames and attrition).
* Serializer options are now consistently used and no longer track references (cycles are just ignored now). Because of prior inconsistencies, existing plugins will fail due to conflicting references if …
=> fix(core): Improve settings handling, hygiene, and error handling

ObservatoryCore/Utils/LogMonitor.cs, ObservatoryFramework/Files/Converters/StationServiceConverter.cs, ObservatoryFramework/Files/Journal/FleetCarrier/CarrierJump.cs, ObservatoryFramework/Files/Journal/FleetCarrier/CarrierLocation.cs, ObservatoryFramework/Files/Journal/Other/ApproachSettlement.cs, ObservatoryFramework/Files/Journal/Powerplay/PowerplayMerits.cs, ObservatoryFramework/Files/Journal/Powerplay/PowerplayRank.cs, ObservatoryFramework/Files/Journal/StationServices/Market.cs, ObservatoryFramework/Files/Journal/Travel/Docked.cs, ObservatoryFramework/Files/Journal/Travel/DockingRequested.cs, ObservatoryFramework/Files/Journal/Travel/FSDJump.cs, ObservatoryFramework/Files/Journal/Travel/Location.cs, ObservatoryFramework/Files/Journal/Travel/Undocked.cs, ObservatoryFramework/Files/MarketFile.cs, ObservatoryFramework/Files/ParameterTypes/Enumerations.cs, ObservatoryFramework/Files/ParameterTypes/Mission.cs, ObservatoryFramework/Files/ParameterTypes/PowerplayStateConflictProgress.cs, ObservatoryFramework/Files/ParameterTypes/WarFaction.cs, ObservatoryFramework/ObservatoryFramework.xml
Looked at recent changes to the jixxed/ed-journal-schemas and patching in PP2.0 and a colonisation change for a missing enum values (for StationService) which can cause some journals to fail to deserialize -- not covered in b944dc1. `StationServiceConverter` is now deprecated in favor of the generic one added in https://github.com/Xjph/ObservatoryCore/commit/b944dc161bdbaf8eee7e32b3e7944b760553bf0d (which appears to work with flag-based enums too). I suspect more colonisation journals will come once the feature is out of beta.
There are a few new localized strings (ie. StationName_Localised -- which would be useful to check if populated).
Of note is the new CarrierLocation event (emitted at game startup) which is now collected and replayed by LogMonitor.
NOTE: I removed the redundant …
=> feat(framework,core): Add support for PP2.0 objects, StationService enum

ObservatoryCore/PluginManagement/PluginCore.cs, ObservatoryCore/UI/CoreSettings.Designer.cs, ObservatoryCore/UI/CoreSettings.cs, ObservatoryCore/Utils/AudioHandler.cs
The recent Herald release exposed some fancy latent bugs (at least for me):
* A race condition that caused voice files from Herald to talk over top of each other. The issue was a race condition in AudioHandler which allowed multiple queue processors to be live at the same time.
* Duplicate notifications (voice and popup) if you also have the StellarOverlay plugin installed and both visual and vocal notifications enabled (but not Plugin). Yeah -- I missed a de-duping corner case in #5e01009.
These are both fixed. I also simplified the logic a bit to make it easier to reason about and added a little chunk of UI in Core Settings to test notification routing/targeting.
=> fix(Core): Fix dupe notifications, cross talk exposed by new Herald

ObservatoryCore/UI/CoreContextMenu.cs, ObservatoryCore/UI/CoreForm.cs
And at the same time fix the assumption that Core is the first tab (resulting in the context menu not working for a plugin in that position).
=> feat(Core): Add a context menu for the core tab

ObservatoryCore/PluginManagement/PluginManager.cs, ObservatoryCore/UI/CoreForm.cs
1. Following up the fix from #220, also show tab context menus on the LAST tab (whether it's Core or a plugin).
2. Prevent duplicate ObservatoryReady calls to plugins with both notifier and worker implementations.
3. And clean up an unused function.
=> fix(core): A few little quick fixes
