Xjph/ObservatoryCore

- ObservatoryCore/PluginManagement/PluginManager.cs
Addresses 2 issues:
1) If a single plugin class implemented both the Worker and Notifier interfaces, multiple instances of the class were created, meaning no shared state within the plugin. Now only 1 instance is created.
2) Plugins implementing only Notifier weren't properly loaded.
> Fixes to PluginManager for proper Notifier plugin handling

- ObservatoryHerald/AzureSpeechManager.cs
The former method lost any XML markup (such as say-as tags, etc) embedded within the voice tag. In the future if support for setting voice speed is added, it can be inserted here easily as well.
> Preserve inner XML when setting a voice style

- ObservatoryCore/LogMonitor.cs
There are a few cases where a jump is not found in the last couple journal files (notably when jumping with a carrier since CarrierJumps went missing in Odyssey -- https://issues.frontierstore.net/issue-detail/46996) that results in ObservatoryCore not pre-reading anything. This PR allows ObservatoryCore to fall back to pre-reading the current journal file to find basic context. This can also help restore context in cases where a stationary user has forgotten to start monitoring after starting the game (ie. mining), or recovering from a crash in ObservatoryCore.
Aside:
For some unknown reason this PR is pulling in a commit related to my last PR (5baa850e2e65d0f055d2652b95c2a07eb88c6828). This shouldn't be an issue and there's no diff caused by it, so just squash commits when merging? My …
> Fall back to pre-reading latest journal file if last jump is not found

- ObservatoryFramework/EventArgs.cs
> Use HasFlag in another spot.

- ObservatoryBotanist/Botanist.cs
Fixes #67 
Tested via read-all and realtime while collecting a sample. 
Required a bit of refactoring to use discrete classes for the main data structure vs. tuples. I think  worked out nicely though.
> Add colony distance support to Botanist grid and notification

- ObservatoryExplorer/Explorer.cs
- ObservatoryExplorer/ExplorerSettings.cs
- ObservatoryExplorer/Worker.cs
Resolves #63
This behavior is suppressed during batch reads.
> Explorer: Show data for the current system only

- ObservatoryExplorer/CustomCriteriaManager.cs
Adds new functions to the Lua environment available to custom criteria for handling rings and belts:
- the existing `rings(scan.Rings)` function behavior is unchanged
- NEW: `ringsOnly(scan.Rings)` and `beltsOnly(scan.Rings)` functions return ONLY rings or belts, respectively, and shortcuts the `scan.Rings` check
- NEW: `hasRings(scan.Rings)` and `hasBelts(scan.Rings)` functions return true if there are one or more proper rings or belts, respectively, in scan.Rings and shortcuts the check, too
Furthermore, this adds a debugging aid that identifies what custom criteria caused an error/crash. For simple criteria, ie:
`::Hot Landable::`
... the description "Hot Landable" is used. For complex criteria, you can now annotate the `::Criteria::` line with a description used for debugging like so: …
> Adds ring/belt helper functions, improved criteria debuggability

- ObservatoryCore/Utils/LogMonitor.cs
CarrierJump w/ OnFoot is needed for many location tracking things -- ATTN MattG as this is causing problems with BioInsights.
I'm requesting Statistics for use by StatsScanner. Did some refactoring around capturing the header lines to be more generic for easier addition of future journal file header-type things.
> [ObservatoryCore] Add Statistics and OnFoot CarrierJumps to preread data

- ObservatoryExplorer/ExplorerUIResults.cs
A small quality-of-life thing.
> [Explorer] Increase column widths to reduce resizing

- ObservatoryExplorer/DefaultCriteria.cs
Observations indicated this would yield a more representative number.
> [Explorer] Include the body radius in the gap calculation

- ObservatoryCore/App.config
- ObservatoryCore/NativeNotification/NativeVoice.cs
- ObservatoryCore/PluginManagement/PluginCore.cs
- ObservatoryCore/Properties/Core.Designer.cs
- ObservatoryCore/Properties/Core.settings
- ObservatoryCore/UI/CoreForm.Designer.cs
- ObservatoryCore/UI/CoreForm.Plugins.cs
- ObservatoryCore/UI/CoreForm.Settings.cs
- ObservatoryCore/UI/CoreForm.cs
- ObservatoryCore/Utils/AudioHandler.cs
Changes to `AudioHandler` and `NativeVoice`:
- Added output device selection to `AudioHandler` and settings
- Added audio file cleanup to `AudioHandler`'s `ProcessQueue` method
- Added `InstantPlay` method to `AudioHandler` for use with sound effects
- Modified `NativeVoice` to use `AudioHandler` for queuing and playback
> [Core] Audio handling improvements

- ObservatoryHerald/HeraldQueue.cs
Leftovers from the old audio player implementation.
> chore(herald): Clean out some old commented code

- ObservatoryCore/Utils/LogMonitor.cs
If file modification time (mtime) is altered in any way (for example, restoring from backup or zip file in a way that does not preserve mtimes, etc.), the ordering of the journal files may become arbitrary and could affect plugin output or violate some assumptions. This parses the timestamp within the filename itself (taking into account both the old and new timestamp formats; see also #66 ) as the authoritative timestamp, falling back to mtime if a timestamp could not be found in the filename.
Tested by adding blank lines to my first journal file. The previous mtime-based logic will now sort this as the most recent file instead of the first in the list. The updated logic introduced here keeps the modified file first in the list.
> fix(core): Sort files by filename timestamp, mtime as fallback

- ObservatoryCore/UI/CoreForm.Designer.cs
- ObservatoryCore/UI/CoreForm.Settings.cs
Range is -10 to 10 but the speed control only allowed 1 to 10.
FWIW, Zira sounds very condescending at -5.
> fix(core): Fix native voice speed slider range to allow slower rates

- ObservatoryCore/UI/SettingsForm.cs
...To match the original intent. :)
Just adding offsets.
> fix(core): Position Settings form in centre of current screen

- ObservatoryCore/NativeNotification/NativeVoice.cs
- ObservatoryCore/Utils/AudioHandler.cs
Repeated "Body X" titles are suppressed something like Herald used to do.
> fix(core): Basic duplicate title suppression for native audio

- ObservatoryBotanist/Botanist.cs
Just use the NotificationArgs variable which now uses the Guid properly.
> chore(botanist): Clean up redundant notification guid variable

- ObservatoryFramework/Files/Journal/Colonisation/ColonisationBeaconDeployed.cs
- ObservatoryFramework/Files/Journal/Colonisation/ColonisationConstructionDepot.cs
- ObservatoryFramework/Files/Journal/Colonisation/ColonisationContribution.cs
- ObservatoryFramework/Files/Journal/Colonisation/ColonisationSystemClaim.cs
- ObservatoryFramework/Files/Journal/Colonisation/ColonisationSystemClaimRelease.cs
- ObservatoryFramework/Files/ParameterTypes/ContributedResource.cs
- ObservatoryFramework/Files/ParameterTypes/RequiredResource.cs
- ObservatoryFramework/Files/ParameterTypes/StoredShip.cs
- ObservatoryFramework/ObservatoryFramework.xml
Updated to jixxed/ed-journal-schemas@82bb340.
There may be more...
> feat(Framework) Add Colonisation journals

- ObservatoryCore/Utils/LogMonitor.cs
Although, maybe a more generic way for plugins to request this would be in order.....
> fix(core): Add Loadout to list of journals to include in pre-read

- ObservatoryCore/PluginManagement/PluginEventHandler.cs
Following up on 071f1da: This change resulted in the cloned message type becoming the string literal "System.Char[]" instead of the intended string. After some further poking around reworked to this to get what I believe was the original intent with the use of `Span` originally.
Also adds the filtering self-sent message implemented by @matt-g-dev in 0c907dd to the pure new-style messages (missed in 3c43fea).
Also, distinguish between the two `On*PluginMessageEvent` methods in the error report.
Finally, move the disabled plugin filter into a `Where` clause that provides the iterator of the `for` loop.
> fix(core): Fix message type cloning and fix filtering of self messages
